settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: prod
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: testApp
    # 端口号
    port: 8977 # 服务端口号
    # 静态文件路由
    staticfileurl: /api/file/download/
    # 静态文件目录
    staticpath: ./static/uploadfile
    # 版本
    version: 0.1.0
  logger:
    # 日志大小
    max_size: 200
    # 日志备份存在天数
    max_age: 30
    # 日志备份数
    max_backups: 7
    # 日志存放路径
    filename: logs/web_app.log
    # 控制台日志
    stdout: true
    # 日志等级
    level: warn
  jwt:
    # token header
    header: Bearer
    # rides user online header
    redis_header: online-token
    # token 密钥，生产环境时及的修改
    secret: ezm9GrpBVGkpfJueE2G@uxu@oziR3$WUkzjqnqxdhN2Rf!qbxiQTtlh$Avd1#^$6
    # token 过期时间 单位：秒
    timeout: 3600
  mysql:
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    # 用户名
    user: root
    # 密码
    password: 123456
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 3306
    # 数据库名
    dbname: bluebell
    # 数据库最大连接数
    maxopen: 20
    # 数据库最大空闲
    maxidle: 20
  redis:
    # redis dns
    # source: redis://120.26.141.144:6379
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    db: 0
    # 最大连接数
    poolsize: 0
    # 最大空闲连接时间
    idletimeoutsec: 240
    # 密码
    password:
